5 view single article
TomMirfin/nc-news pull request #3
Opened 2023-12-11 14:13 UTC by TomMirfin

2023-12-11 15:52 UTC, 2202Hannah requested changes
Hey Tom, nice work on task 5 so far. 

When I select an article on the first page and it takes me to your single article route I can only see the `Loading your article` message and the single article itself doesn't render. Please can you fix this and submit another pr when you are ready?

2023-12-11 15:52 UTC, 2202Hannah commented on src/App.jsx
> +        <Route path="/articles/:article_id" element={<SingleArticle />} />
nice 👍

2023-12-12 10:54 UTC, 2202Hannah commented on src/App.jsx
> +        <Route path="/articles/:id" element={<SingleArticle />} />
Your routes are set up well 👍

2023-12-12 11:12 UTC, 2202Hannah requested changes
Hey Tom, great work so far. Please see my in line comments. Once you have made the changes you can either merge to main or submit another pr if you would like us to check over the code.

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/ArticleCard.jsx
> +import { useParams } from "react-router-dom";
You could import Link and useParams together as they are both from react-router-dom e.g. {Link, useParams}, although I'm not sure you use useParams in this component so it may be best to remove if not needed

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/ArticleCard.jsx
> +        <img src={article.article_img_url} alt="" />
Could you use something from the article object in alt to make your app more accessible?

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/ArticleCard.jsx
> +          <Link to={`/articles/${article.article_id}`}>
You have doubled up here by having both a Link to your articles/:article_id route and a ternary in Articles.jsx that is triggered by the onClick in your button. I would let your Link handle this functionality as the user will navigate to a new path and subsequently the SingleArticle component will render independently from the Articles component.

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/SingleArticle.jsx
> +  console.log(article);
please make sure you remove any console.logs before merging to main

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/SingleArticle.jsx
> +  const { id } = useParams();
nice 👍

2023-12-12 11:12 UTC, 2202Hannah commented on src/components/SingleArticle.jsx
> +        <img src={article[0].article_img_url} alt="" />
Could you add something to your alt tag to make your app more accessible?

2023-12-12 14:30 UTC, Harrison365 commented on src/components/ArticleCard.jsx
> +            <Button
Excellent changes.
Good to go 😄

2023-12-12 14:31 UTC, merged